name: kopiek_resto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  path_provider: ^2.0.5
  equatable: ^2.0.3
  dartz: ^0.10.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  flutter_bloc: ^7.3.1
  dio: ^4.0.1
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2
  timeline_tile: ^2.0.0
  flutter_easyloading: ^3.0.3
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.1.0
  shared_preferences: ^2.0.8
  flare_flutter: ^3.0.2
  freezed_annotation: ^0.15.0
  injectable: ^1.5.0
  image_picker: ^0.8.4+4
  flutter_exif_rotation: ^0.4.2
  permission_handler: ^8.3.0
  webview_flutter: ^3.0.0
  onesignal_flutter: ^3.3.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  freezed: ^0.15.0+1
  build_runner: ^2.1.4
  injectable_generator: ^1.5.2

flutter:


  uses-material-design: true


  assets:
   - assets/animation/
   - assets/

